apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-ns
data:
  DB_HOST: db.db-ns.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: mensagensdb
  API_HOST: "0.0.0.0"
  API_PORT: "5000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: app-ns
data:
  VITE_API_URL: "http://localhost:30081/api"

